spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customers
    username: postgres
    password: rayana2015
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath*:database/initDB.sql
      data-locations: classpath*:database/populateDB.sql